import type { Issue } from "./types";

export const mockIssues: Issue[] = [
  {
    id: "demo-1",
    creatorName: "Nguyễn Văn Toàn",
    category: "Cao độ trần, đường ống kỹ thuật tuyến trục",
    content: "Hiện nay cao độ đường ống trên trần của khu vực hành lang đang bị chồng chéo với hệ thống MEP khác. Đề nghị kiểm tra lại mặt bằng phối hợp và đưa ra cao độ thống nhất.",
    attachments: [{ name: "MEP-01.pdf", url: "#", kind: "file", mimeType: "application/pdf" }],
    createdAt: "2025-07-14T07:26:00+07:00",
    reply: "Bảng thông tin sẽ được cập nhật trong buổi họp phối hợp kỹ thuật tiếp theo.",
    responderName: "Nguyễn Văn Sáu",
    repliedAt: "2025-07-14T09:10:00+07:00",
    status: "Đã trả lời",
  },
  {
    id: "demo-2",
    creatorName: "Nguyễn Quốc Bảo",
    category: "Biện pháp thi công phần kết cấu",
    content: "Bề mặt sàn khu vực lõi thang đang có chênh cao so với bản vẽ phát hành. Cần xác nhận cao độ thi công và cập nhật chi tiết tại vị trí giao nhau.",
    attachments: [{ name: "Chi-tiet-san.dwg", url: "#", kind: "file", mimeType: "application/acad" }],
    createdAt: "2025-07-14T08:12:00+07:00",
    reply: "Đã chuyển nội dung cho bộ phận kết cấu kiểm tra và phản hồi trong ngày.",
    responderName: "Trần Minh Đức",
    repliedAt: "2025-07-14T10:05:00+07:00",
    status: "Đã trả lời",
  },
  {
    id: "demo-3",
    creatorName: "Vũ Hoàng Nam",
    category: "Mục M1, M2 của đường LCC-NC-02",
    content: "Kích thước móng trên bản vẽ đang khác với hồ sơ khảo sát hiện trường. Đề nghị xác nhận lại trước khi triển khai cốt thép.",
    attachments: [],
    createdAt: "2025-07-14T09:40:00+07:00",
    reply: "",
    responderName: "",
    repliedAt: null,
    status: "Đang xử lý",
  },
  {
    id: "demo-4",
    creatorName: "VCI - Nguyễn Đoàn",
    category: "Kích thước và cao độ sàn",
    content: "Mặt bằng hiện tại chưa thể hiện rõ vị trí khe co giãn tại khu vực sảnh. Cần bổ sung chi tiết để đội thi công đối chiếu.",
    attachments: [{ name: "Mat-bang-tang-1.png", url: "#", kind: "file", mimeType: "image/png" }],
    createdAt: "2025-07-13T13:32:00+07:00",
    reply: "Đã ghi nhận và đang phối hợp với nhóm thiết kế để cập nhật bản vẽ.",
    responderName: "Lê Anh Tú",
    repliedAt: "2025-07-13T16:22:00+07:00",
    status: "Đã trả lời",
  },
  {
    id: "demo-5",
    creatorName: "VCI - Nguyễn Đoàn",
    category: "Kích thước hình học bản vẽ",
    content: "Xem xét lại các thông số dẫn xuất trong bảng thống kê để thống nhất với hồ sơ phát hành.",
    attachments: [{ name: "https://drive.google.com/example", url: "https://drive.google.com", kind: "link" }],
    createdAt: "2025-07-13T14:05:00+07:00",
    reply: "Đã cập nhật thông số theo phiên bản hồ sơ mới nhất.",
    responderName: "Trần Minh Đức",
    repliedAt: "2025-07-14T08:18:00+07:00",
    status: "Đã trả lời",
  },
];
